"""
The ipynb package contains a script to test ipython notebooks
similar to testing python code using nosetests.

"""

# from distutils.core import setup
from setuptools import setup
import os
import subprocess

##########################
VERSION = "0.2.1"
ISRELEASED = False
__version__ = VERSION
##########################

################################################################################
# Writing version control information to the module
################################################################################


def git_version():
    # Return the git revision as a string
    # copied from numpy setup.py
    def _minimal_ext_cmd(cmd):
        # construct minimal environment
        env = {}
        for k in ['SYSTEMROOT', 'PATH']:
            v = os.environ.get(k)
            if v is not None:
                env[k] = v
        # LANGUAGE is used on win32
        env['LANGUAGE'] = 'C'
        env['LANG'] = 'C'
        env['LC_ALL'] = 'C'
        out = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, env=env).communicate()[0]
        return out

    try:
        out = _minimal_ext_cmd(['git', 'rev-parse', 'HEAD'])
        GIT_REVISION = out.strip().decode('ascii')
    except OSError:
        GIT_REVISION = 'Unknown'

    return GIT_REVISION


def write_version_py(filename='ipynbtest/version.py'):
    cnt = """
# This file is automatically generated by setup.py
short_version = '%(version)s'
version = '%(version)s'
full_version = '%(full_version)s'
git_revision = '%(git_revision)s'
release = %(isrelease)s

if not release:
    version = full_version
"""
    # Adding the git rev number needs to be done inside write_version_py(),
    # otherwise the import of numpy.version messes up the build under Python 3.
    FULLVERSION = VERSION
    if os.path.exists('.git'):
        GIT_REVISION = git_version()
    else:
        GIT_REVISION = 'Unknown'

    if not ISRELEASED:
        FULLVERSION += '.dev-' + GIT_REVISION[:7]

    a = open(filename, 'w')
    try:
        a.write(cnt % {'version': VERSION,
                       'full_version': FULLVERSION,
                       'git_revision': GIT_REVISION,
                       'isrelease': str(ISRELEASED)})
    finally:
        a.close()

################################################################################
# Installation
################################################################################

write_version_py()


def buildKeywordDictionary():
    setupKeywords = {}
    setupKeywords["name"]              = "ipynbtest"
    setupKeywords["version"]           = "0.2.1"
    setupKeywords["author"]            = "Jan-Hendrik Prinz"
    setupKeywords["author_email"]      = "jan.prinz@choderalab.org"
    setupKeywords["license"]           = "GPL 2.0"
    setupKeywords["url"]               = "http://github.com/jhprinz/ipynb-test"
    setupKeywords["download_url"]      = "http://github.com/jhprinz/ipynb-test"
    setupKeywords["packages"]          = ['ipynbtest']
    setupKeywords["package_dir"]       = {
        'ipynbtest': 'ipynbtest',
    }
    setupKeywords["scripts"]           = ['ipynbtest/ipynbtest.py']
    setupKeywords["data_files"]        = []
    setupKeywords["ext_modules"]       = []
    setupKeywords["platforms"]         = ["Linux", "Mac OS X", "Windows"]
    setupKeywords["description"]       = "Python script to test IPython notebooks."
    setupKeywords["requires"]          = []
    setupKeywords["long_description"]  = """
    ipynb-test (http://github.com/jhprinz/ipynb-test) is a python script to test ipython notebooks (.ipynb) files.
    It has additional support for integration in travis.
    """
    outputString=""
    firstTab     = 40
    secondTab    = 60
    for key in sorted(setupKeywords):
         value         = setupKeywords[key]
         outputString += key.rjust(firstTab) + str( value ).rjust(secondTab) + "\n"
    
    print("%s" % outputString)

    return setupKeywords
    

def main():
    setupKeywords = buildKeywordDictionary()
    setup(**setupKeywords)

if __name__ == '__main__':
    main()
