
# This file is automatically generated by setup.py
short_version = '0.2.1'
version = '0.2.1'
full_version = '0.2.1.dev-b34737d'
git_revision = 'b34737d7274279379bc5a752249962a819b6acdf'
release = False

if not release:
    version = full_version
