
# This file is automatically generated by setup.py
short_version = '0.2.1'
version = '0.2.1'
full_version = '0.2.1.dev-7a45f08'
git_revision = '7a45f0846b1bc15552ccdf712cd31d68075d8873'
release = False

if not release:
    version = full_version
