
# This file is automatically generated by setup.py
short_version = '0.2.1'
version = '0.2.1'
full_version = '0.2.1.dev-1302ba8'
git_revision = '1302ba87ef5d916d810a4fa0c52303e0fea4a1fd'
release = False

if not release:
    version = full_version
